version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ledger
      SPRING_DATASOURCE_USERNAME: ledger
      SPRING_DATASOURCE_PASSWORD: ledger
      jwt.secret: VerySecretKeyChangeMeInProdVerySecretKey
    ports:
      - "8080:8080"
    depends_on:
      - db
